//|              URL     | Method |                Why?                       |                          Request                           |                     Response Data                         | Codes                         |
//|:--------------------:|:------:|-------------------------------------------|:----------------------------------------------------------:|:---------------------------------------------------------:|-------------------------------|
//| '/api/users/'        | POST   | Create a new user                         | { username: String, password: String }                     | { authToken: String }                                     | 201, OK 403, Forbidden        |
//| '/api/users/'        | DELETE | Remove a user from the database           | user decoded from token and { password: String }           |                                                           | 200, OK 401, Unauthorized     |
//| '/api/login/'        | POST   | Login a user                              | { username: String, password: String }                     | { username: String, authToken: String }                   | 201, OK 401, Unauthorized     |
//| '/api/auth/'         | GET    | Check user authorization                  | No data                                                    | Status Code                                               | 200, OK 401, Unauthorized     |
//|                      |        |                                           |                                                            |                                                           |                               |
//| '/api/generateTable:?usr=<username>'                    | POST   | Add the users schema to the database      | query.usr= username and a json object with fields to create       | {schema: schema }                                         | 201, OK 401, Unauthorized     |
//| '/api/retrieveOneTable:?usrTable=<username_table>'       | GET    | Retrieve one schema                 | query.usrTable= tableName                                           | {schema: schema }                                         | 200, OK 401, Unauthorized     |
//| '/api/retrieveTables:?usr=<username>'               | GET    | Retrieve all table names from a user                 | query.usr= username}                                           | {schema: schema }                                         | 200, OK 401, Unauthorized     |//|             
         |        |                                                                                                       |                                                           |                               |
//| '/api/:username'     | GET    | Retrieve the users data                   | params.username                                            | { field1: String, field2: String, field3: String, ....}   | 200, OK 404, Not found        |
//| '/api/:username'     | POST   | Add to the users data                     | params.username                                            | No data                                                   | 201, OK 404, Not found        |
//| '/api/:username'     | PUT    | Update the users data                     | params.username and field to be updated passed in params   | updated field                                             | 200, OK 404, Not found        |
//| '/api/:username'     | DELETE | Delete the users data                     | params.username and field to be deleted passed in params   | deleted field                                             | 200, OK 404, Not found        |