//|              URL                             | Method |                Why?                       |                          Request                           |                     Response Data                         | Codes                         |
//|:--------------------------------------------:|:------:|-------------------------------------------|:----------------------------------------------------------:|:---------------------------------------------------------:|-------------------------------|
//| '/api/users/'                                | POST   | Create a new user                         | { username: String, password: String }                     | { authToken: String }                                     | 201, OK 403, Forbidden        |
//| '/api/users/'                                | DELETE | Remove a user from the database           | user decoded from token and { password: String }           |                                                           | 200, OK 401, Unauthorized     |
//| '/api/login/'                                | POST   | Login a user                              | { username: String, password: String }                     | { username: String, authToken: String }                   | 201, OK 401, Unauthorized     |
//| '/api/auth/'                                 | GET    | Check user authorization                  | No data                                                    | Status Code                                               | 200, OK 401, Unauthorized     |
//|                                              |        |                                           |                                                            |                                                           |                               |
//| '/api/generateTable:?usr=<username>'         | POST   | Add the users schema to the database      | query.usr= username and a json obj with fields to create   | Status Code                                               | 201, OK 401, Unauthorized     |
//| '/api/getOneTable:?usrTable=<username_table>'| GET    | Retrieve one schema                       | query.usrTable= tableName                                  | JSON of 1 table                                           | 200, OK 401, Unauthorized     |
//| '/api/getTables:?usr=<username>'             | GET    | Retrieve all table names from a user      | query.usr= username}                                       | JSON of all a users tableNames                            | 200, OK 401, Unauthorized     |             
//|                                              |        |                                           |                                                            |                                                           |                               |
//| '/api/postToTable:?usr=<username>'           | POST   | Add a row to a users table                | object with tableName & row to post {newColumn: newValue}  | Status Code                                               | 201, OK 404, Not found        |
//| '/api/updateValue:?usr=<username>'           | PUT    | Update the users data                     | object with tableName columnName, oldValue, newValue       | updated field                                             | 200, OK 404, Not found        |
//| '/api/deleteTable:?usr=<username>'           | DELETE | Delete a users table                      | object with tableName                                      | deleted tableName                                         | 200, OK 404, Not found        |
//| '/api/deleteRow:?usr=<username>'             | DELETE | Delete a row in a users table             | object with tableName, columnName, and value in the column | Status Code                                               | 200, OK 404, Not found        |
