//|              URL                             | Method |                Why?                                 |                          Request                                                         |                     Response Data                         | Codes                         |
//|:--------------------------------------------:|:------:|-----------------------------------------------------|:----------------------------------------------------------------------------------------:|:---------------------------------------------------------:|-------------------------------|
//| '/api/users/'                                | POST   | Create a new local                                  | { username: String, password: String }                                                   | redirects to /#/signin on success                         | 403, Forbidden                |
//| '/api/users/'                                | DELETE | Remove a user from the database                     | user decoded from token and { password: String }                                         |                                                           | 200, OK 401, Unauthorized     |
//| '/signin'                                    | POST   | Login a local                                       | { username: String, password: String }                                                   | redirects to /#/create on success                         |                               |
//| '/auth/github'                               | GET    | GitHub authentication                               | No data                                                                                  | reroutes                                                  | 200, OK 401, Unauthorized     |
//| '/auth/github/callback'                      | GET    | GitHub authentication                               | No data                                                                                  | redirects to /#/create on success                         | 200, OK 401, Unauthorized     |
//| '/user'                                      | GET    | returns signed in user to client                    | No data                                                                                  | saves sift-user to localStorage                           | 200, OK 401, Unauthorized     |
//| '/logout'                                    | GET    | ends server session                                 | No data                                                                                  | redirects to /#/signin                                    |                               |
//|                                              |        |                                                     |                                                                                          |                                                           |                               |
//| '/api/users/tables'                          | GET    | Retrieve all table names from a user                | No data                                                                                  | JSON of all a users tableNames                            | 200, OK 401, Unauthorized     |             
//| '/api/users/tables'                          | POST   | Adds a user's schema to the database                | JSON obj with fields to create                                                           | Status Code                                               | 200, OK 401, Unauthorized     |
//| '/api/users/tables'                          | DELETE | Retrieve one schema                                 | req.body : { tableName: String }                                                         | JSON of 1 table                                           | 200, OK 401, Unauthorized     |
//|                                              |        |                                                     |                                                                                          |                                                           |                               |
//| '/sand/:tablename/:username'                 | GET    | External endpoint for user to retreives a table     | params : tablename, username                                                             | array of JSON data rows                                   | 200, OK 400, Bad request      |
//| '/sand/:tablename/:username'                 | POST   | External endpoint for user to add row to a table    | params : tablename, username & req.body : { columnname: value }                          | Status Code                                               | 200, OK 400, Bad request      |
//| '/sand/:tablename/:username/:rowId           | PUT    | External endpoint for user to update row of a table | params : tablename, username, rowId & req.body : { columnName: String, newVaule: value } | Status Code                                               | 200, OK 400, Bad request      |
//| '/sand/:tablename/:username/:rowId           | DELETE | External endpoint for user to delete row of a table | params : tablename, username, rowId                                                      | Status Code                                               | 200, OK 400, Bad request      |
//|                                              |        |                                                     |                                                                                          |                                                           |                               |
